# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/temp/tradingUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(255,255,255)")

        # 검색창
        self.edit_search = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_search.setGeometry(QtCore.QRect(170, 40, 480, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.edit_search.setFont(font)
        self.edit_search.setObjectName("edit_search")

        # 검색창 돋보기 이미지
        self.image_search = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_search.setGeometry(QtCore.QRect(125, 40, 35, 35))
        self.image_search.setStyleSheet("border-image: url(resources/search.png); background-repeat: no-repeat;")
        self.image_search.setObjectName("image_search")

        # 왼쪽 프레임
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 80, 981, 1021))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("background-color:none;")

        # 코인이미지
        self.image_coin = QtWidgets.QGraphicsView(self.frame)
        self.image_coin.setGeometry(QtCore.QRect(130, 10, 35, 35))
        self.image_coin.setStyleSheet("border-image: url(resources/bitcoin.png); background-repeat: no-repeat;")
        self.image_coin.setObjectName("image_coin")

        # 코인명(예.비트코인)
        self.label_coinName = QtWidgets.QLabel(self.frame)
        self.label_coinName.setGeometry(QtCore.QRect(174, 10, 200, 50))
        self.label_coinName.setObjectName("label_coinName")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_coinName.setFont(font)

        # 코인명 옆에 회색으로 알파벳 코드(예.BTC)
        self.label_coinNickname = QtWidgets.QLabel(self.frame)
        self.label_coinNickname.setGeometry(QtCore.QRect(250, 3, 150, 70))
        self.label_coinNickname.setObjectName("label_coinNickname")
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_coinNickname.setFont(font)
        self.label_coinNickname.setStyleSheet("color: GREY;")

        # 구분선1
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(126, 40, 800, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # 코인 시가
        self.label_101 = QtWidgets.QLabel(self.frame)
        self.label_101.setGeometry(QtCore.QRect(25, 50, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label_101.setFont(font)
        self.label_101.setStyleSheet("color: RED;")
        self.label_101.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_101.setObjectName("label_101")


        # KRW
        self.label_102 = QtWidgets.QLabel(self.frame)
        self.label_102.setGeometry(QtCore.QRect(63, 57, 300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_102.setFont(font)
        self.label_102.setStyleSheet("color: RED;")
        self.label_102.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_102.setObjectName("label_102")

        # 전일대비
        self.label_103 = QtWidgets.QLabel(self.frame)
        self.label_103.setGeometry(QtCore.QRect(133, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")

        # 상승폭
        self.label_104 = QtWidgets.QLabel(self.frame)
        self.label_104.setGeometry(QtCore.QRect(200, 80, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_104.setFont(font)
        self.label_104.setStyleSheet("color: RED;")
        self.label_104.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_104.setObjectName("label_104")

        # 고가
        self.label_105 = QtWidgets.QLabel(self.frame)
        self.label_105.setGeometry(QtCore.QRect(450, 60, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")

        # 고가 금액
        self.label_106 = QtWidgets.QLabel(self.frame)
        self.label_106.setGeometry(QtCore.QRect(500, 60, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_106.setFont(font)
        self.label_106.setStyleSheet("color: RED;")
        self.label_106.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_106.setObjectName("label_106")

        # 거래량(24H)
        self.label_107 = QtWidgets.QLabel(self.frame)
        self.label_107.setGeometry(QtCore.QRect(680, 60, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")

        # 거래량
        self.label_108 = QtWidgets.QLabel(self.frame)
        self.label_108.setGeometry(QtCore.QRect(800, 60, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        # 구분선1
        self.line1 = QtWidgets.QFrame(self.frame)
        self.line1.setGeometry(QtCore.QRect(420, 76, 500, 16))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")




        # 저가
        self.label_109 = QtWidgets.QLabel(self.frame)
        self.label_109.setGeometry(QtCore.QRect(450, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")

        # 저가 금액
        self.label_110 = QtWidgets.QLabel(self.frame)
        self.label_110.setGeometry(QtCore.QRect(500, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_110.setFont(font)
        self.label_110.setStyleSheet("color: BLUE;")
        self.label_110.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_110.setObjectName("label_110")

        # 거래대금(24H)
        self.label_111 = QtWidgets.QLabel(self.frame)
        self.label_111.setGeometry(QtCore.QRect(680, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")

        # 거래대금
        self.label_112 = QtWidgets.QLabel(self.frame)
        self.label_112.setGeometry(QtCore.QRect(780, 90, 150, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")





        # 과거 데이터 테스트
        self.back_trading = QtWidgets.QLabel(self.frame)
        self.back_trading.setGeometry(QtCore.QRect(125, 120, 200, 50))
        self.back_trading.setObjectName("back_trading")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.back_trading.setFont(font)


        # 전략 선택
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(130, 160, 130, 35))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("  터틀 전략")
        self.comboBox.addItem("  전략 2번")
        self.comboBox.addItem("  전략 3번")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border: 1px solid blue; background-color:white; color: black;")

        # 일 버튼
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(290, 159, 40, 38))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("border: 1px solid grey; background-color:blue; color: white;")

        # 주 버튼
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setGeometry(QtCore.QRect(335, 159, 40, 38))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.setStyleSheet("border: 1px solid grey; background-color:blue; color: white;")

        # 월 버튼
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 159, 40, 38))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("border: 1px solid grey; background-color:blue; color: white;")

        # 년 버튼
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(425, 159, 40, 38))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("border: 1px solid grey; background-color:blue; color: white;")

        # 테스트 버튼
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 159, 70, 38))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("border: 1px solid blue; background-color:white; color: blue;")

        # 수익률
        self._yield = QtWidgets.QLabel(self.frame)
        self._yield.setGeometry(QtCore.QRect(640, 155, 200, 50))
        self._yield.setObjectName("_yield")
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self._yield.setFont(font)

        # 오른쪽 프레임
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:none;")
        self.frame_2.setGeometry(QtCore.QRect(948, 0, 683, 768))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")



        # 왼쪽 메뉴 프레임
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 100, 768))
        self.frame.setStyleSheet("background-color: rgb(50, 90, 160)")  # 배경색 설정
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # 오른쪽 프레임
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:none;")
        self.frame_2.setGeometry(QtCore.QRect(948, 0, 683, 768))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        # 보유종목
        self.comboBox1 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox1.setGeometry(QtCore.QRect(0, 30, 130, 35))
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("보유종목")
        self.comboBox1.addItem("doge")
        self.comboBox1.addItem("btc")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.comboBox1.setFont(font)
        self.comboBox1.setStyleSheet("border: 1px solid blue; background-color:white; color: black;")

        # 주문가능
        self.label_114 = QtWidgets.QLabel(self.frame_2)
        self.label_114.setGeometry(QtCore.QRect(10, 120, 200, 50))
        self.label_114.setObjectName("label_114")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_114.setFont(font)

        # 주문금액
        self.label_115 = QtWidgets.QLabel(self.frame_2)
        self.label_115.setGeometry(QtCore.QRect(250, 120, 200, 50))
        self.label_115.setObjectName("label_115")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_115.setFont(font)
        # 10%
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 170, 40, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("border: 1px solid grey; background-color:white; color: black;")
        # 20%
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 170, 40, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet("border: 1px solid grey; background-color:white; color: black;")
        # 50%
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 170, 40, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet("border: 1px solid grey; background-color:white; color: black;")
        # 100%
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 170, 40, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet("border: 1px solid grey; background-color:white; color: black;")
        # 직접입력
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 170, 60, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet("border: 1px solid grey; background-color:white; color: black;")

        # 주문총액
        self.label_116 = QtWidgets.QLabel(self.frame_2)
        self.label_116.setGeometry(QtCore.QRect(10, 220, 200, 50))
        self.label_116.setObjectName("label_116")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_116.setFont(font)

        # 검색창
        self.edit_search_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_search_1.setGeometry(QtCore.QRect(1070, 227, 218, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.edit_search_1.setFont(font)
        self.edit_search_1.setObjectName("edit_search_1")

        #자동 매매 시작
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 280, 160, 42))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet("border: 1px solid grey; background-color:red; color: white;")
        # 자동 매매 종료
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setGeometry(QtCore.QRect(190, 280, 160, 42))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet("border: 1px solid grey; background-color:blue; color: white;")
        # 구분선2
        self.line2 = QtWidgets.QFrame(self.frame_2)
        self.line2.setGeometry(QtCore.QRect(0, 350, 370, 16))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        # 자동 매매 거래 내역
        self.label_117 = QtWidgets.QLabel(self.frame_2)
        self.label_117.setGeometry(QtCore.QRect(0, 380, 200, 50))
        self.label_117.setObjectName("label_117")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_117.setFont(font)

        # 자동매매 거래 내역 리스트
        self.table_currentCoinList = QtWidgets.QTableWidget(self.frame_2)
        self.table_currentCoinList.setGeometry(QtCore.QRect(0, 420, 370, 330))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_currentCoinList.sizePolicy().hasHeightForWidth())
        self.table_currentCoinList.setSizePolicy(sizePolicy)
        self.table_currentCoinList.setMouseTracking(False)
        self.table_currentCoinList.setStyleSheet(
            """
            QHeaderView::section {
                background-color:#404040;
                color:#FFFFFF;
            }
            """
        )
        self.table_currentCoinList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_currentCoinList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_currentCoinList.setAutoScrollMargin(16)
        self.table_currentCoinList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.table_currentCoinList.setAlternatingRowColors(True)
        self.table_currentCoinList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_currentCoinList.setRowCount(30)
        self.table_currentCoinList.setColumnCount(5)
        self.table_currentCoinList.setObjectName("table_currentCoinList")
        item = QtWidgets.QTableWidgetItem()
        self.table_currentCoinList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_currentCoinList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_currentCoinList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_currentCoinList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_currentCoinList.setHorizontalHeaderItem(4, item)

        self.table_currentCoinList.horizontalHeader().setVisible(True)
        self.table_currentCoinList.horizontalHeader().setFixedHeight(45)
        self.table_currentCoinList.horizontalHeader().setDefaultSectionSize(70)  # 테이블 기본 열 크기
        self.table_currentCoinList.horizontalHeader().setSortIndicatorShown(True)
        self.table_currentCoinList.horizontalHeader().setStretchLastSection(False)
        self.table_currentCoinList.verticalHeader().setVisible(False)  # 행 번호 안보이게 설정
        self.table_currentCoinList.verticalHeader().setCascadingSectionResizes(False)
        self.table_currentCoinList.verticalHeader().setDefaultSectionSize(35)  # 테이블 기본 행 크기
        self.table_currentCoinList.verticalHeader().setHighlightSections(True)

        # 메뉴-마이페이지 버튼
        self.menuButton_myPage_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_myPage_3.setGeometry(QtCore.QRect(21, 50, 60, 60))
        self.menuButton_myPage_3.setObjectName("menuButton_myPage_3")
        self.menuButton_myPage_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_myPage.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_myPage_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-트레이딩 버튼
        self.menuButton_trading_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_trading_3.setGeometry(QtCore.QRect(21, 150, 60, 60))
        self.menuButton_trading_3.setObjectName("menuButton_trading_3")
        self.menuButton_trading_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_trading.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_trading_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-거래(사고팔기) 버튼
        self.menuButton_chart_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_chart_3.setGeometry(QtCore.QRect(21, 250, 60, 60))
        self.menuButton_chart_3.setObjectName("menuButton_chart_3")
        self.menuButton_chart_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_chart.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_chart_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-자동거래 버튼
        self.menuButton_autoTrading_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_autoTrading_3.setGeometry(QtCore.QRect(21, 350, 60, 60))
        self.menuButton_autoTrading_3.setObjectName("menuButton_autoTrading_3")
        self.menuButton_autoTrading_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_autoTrading.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_autoTrading_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-환경설정 버튼
        self.menuButton_setting_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_setting_3.setGeometry(QtCore.QRect(21, 450, 60, 60))
        self.menuButton_setting_3.setObjectName("menuButton_setting_3")
        self.menuButton_setting_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_setting.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_setting_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-종료 버튼
        self.menuButton_exit_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_exit_3.setGeometry(QtCore.QRect(21, 650, 60, 60))
        self.menuButton_exit_3.setObjectName("menuButton_exit_3")
        self.menuButton_exit_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_exit.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_exit_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_coinName.setText(_translate("MainWindow", "비트코인"))
        self.label_coinNickname.setText(_translate("MainWindow", "BTC/KRW"))
        # self.label_3.setText(_translate("MainWindow", "호가"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "일괄취소"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "9,999"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "수량(BTC)"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "9,999"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "일괄취소"))
        # self.label.setText(_translate("MainWindow", "거래량"))
        # self.label_2.setText(_translate("MainWindow", "거래대금"))
        # self.label_4.setText(_translate("MainWindow", "6,875"))
        # self.label_5.setText(_translate("MainWindow", "BTC"))
        # self.label_6.setText(_translate("MainWindow", "472,668"))
        # self.label_7.setText(_translate("MainWindow", "백만원"))
        # self.label_8.setText(_translate("MainWindow", "(최근 24시간)"))
        # self.label_9.setText(_translate("MainWindow", "52주 최고"))
        # self.label_10.setText(_translate("MainWindow", "81,994,000"))
        # self.label_11.setText(_translate("MainWindow", "(2021.04.14)"))
        # self.label_12.setText(_translate("MainWindow", "81,994,000"))
        # self.label_13.setText(_translate("MainWindow", "(2021.04.14)"))
        # self.label_14.setText(_translate("MainWindow", "52주 최저"))
        # self.label_15.setText(_translate("MainWindow", "81,994,000"))
        # self.label_17.setText(_translate("MainWindow", "81,994,000"))
        # self.label_19.setText(_translate("MainWindow", "당일고가"))
        # self.label_20.setText(_translate("MainWindow", "81,994,000"))
        # self.label_22.setText(_translate("MainWindow", "당일저가"))
        # self.label_18.setText(_translate("MainWindow", "+3.35%"))
        # self.label_21.setText(_translate("MainWindow", "-0.37%"))
        # self.label_40.setText(_translate("MainWindow", "9,999"))
        # self.label_41.setText(_translate("MainWindow", "9,999"))
        # self.button_cancel_1.setText(_translate("MainWindow", "일괄취소"))
        # self.button_cancel_2.setText(_translate("MainWindow", "일괄취소"))
        # self.button_quantity.setText(_translate("MainWindow", "수량(BTC)"))
        self.pushButton.setText(_translate("MainWindow", "일"))
        self.pushButton_1.setText(_translate("MainWindow", "주"))
        self.pushButton_2.setText(_translate("MainWindow", "월"))
        self.pushButton_3.setText(_translate("MainWindow", "년"))
        self.pushButton_4.setText(_translate("MainWindow", "테스트"))
        self.pushButton_5.setText(_translate("MainWindow", "10%"))
        self.pushButton_6.setText(_translate("MainWindow", "20%"))
        self.pushButton_7.setText(_translate("MainWindow", "50%"))
        self.pushButton_8.setText(_translate("MainWindow", "100%"))
        self.pushButton_9.setText(_translate("MainWindow", "자동매매"))
        self.pushButton_10.setText(_translate("MainWindow", "종료하기"))
        self.pushButton_11.setText(_translate("MainWindow", "직접입력"))
        self.label_101.setText(_translate("MainWindow", "81,994,000"))
        self.label_102.setText(_translate("MainWindow", "KRW"))
        self.label_103.setText(_translate("MainWindow", "전일대비"))
        self.label_104.setText(_translate("MainWindow", "+0.91%▲ 610,000"))
        self.label_105.setText(_translate("MainWindow", "고가"))
        self.label_106.setText(_translate("MainWindow", "68,280,000"))
        self.label_107.setText(_translate("MainWindow", "거래량(24H)"))
        self.label_108.setText(_translate("MainWindow", "7,052.103 BTC"))
        self.label_109.setText(_translate("MainWindow", "저가"))
        self.label_110.setText(_translate("MainWindow", "66,350,000"))
        self.label_111.setText(_translate("MainWindow", "거래대금(24H)"))
        self.label_112.setText(_translate("MainWindow", "484, 272,350,212 KRW"))
        self.label_114.setText(_translate("MainWindow", "주문가능"))
        self.label_115.setText(_translate("MainWindow", "10,000KRW"))
        self.label_116.setText(_translate("MainWindow", "주문총액(KRW)"))
        self.label_117.setText(_translate("MainWindow", "자동 매매 거래 내역"))
        self.back_trading.setText(_translate("MainWindow", "과거 데이터 테스트"))
        self._yield.setText(_translate("MainWindow", "수익률 : 0%"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
