# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/temp/tradingUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: rgb(255,255,255)")

        # 중앙프레임
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:none;")
        self.frame_2.setGeometry(QtCore.QRect(200, 100, 1500, 1079))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")





        # 이름 텍스트
        self.label_Name = QtWidgets.QLabel(self.frame_2)
        self.label_Name.setGeometry(QtCore.QRect(320, 10, 281, 70))
        self.label_Name.setObjectName("label_Name")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label_Name.setFont(font)


        # 비밀번호변경 텍스트
        self.label_change = QtWidgets.QLabel(self.frame_2)
        self.label_change.setGeometry(QtCore.QRect(307, 150, 281, 70))
        self.label_change.setObjectName("label_change")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.label_change.setFont(font)


        # 현재비밀번호 텍스트
        self.current_password = QtWidgets.QLabel(self.frame_2)
        self.current_password.setGeometry(QtCore.QRect(372, 200, 211, 98))
        self.current_password.setObjectName("current_password")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.current_password.setFont(font)
        self.current_password.setStyleSheet("color: GREY;")

        # 현재 비밀번호 입력창
        self.input_current_password = QtWidgets.QLineEdit(self.frame_2)
        self.input_current_password.setGeometry(QtCore.QRect(600, 220, 500, 49))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_current_password.setFont(font)
        self.input_current_password.setObjectName("input_current_password")



        # 새 비밀번호 텍스트
        self.new_password = QtWidgets.QLabel(self.frame_2)
        self.new_password.setGeometry(QtCore.QRect(372, 300, 211, 98))
        self.new_password.setObjectName("new_password")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.new_password.setFont(font)
        self.new_password.setStyleSheet("color: GREY;")

        # 새 비밀번호 입력창
        self.input_new_password = QtWidgets.QLineEdit(self.frame_2)
        self.input_new_password.setGeometry(QtCore.QRect(600, 320, 500, 49))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_new_password.setFont(font)
        self.input_new_password.setObjectName("input_new_password")


        # 새 비밀번호 확인 텍스트
        self.new_password2 = QtWidgets.QLabel(self.frame_2)
        self.new_password2.setGeometry(QtCore.QRect(372, 400, 211, 98))
        self.new_password2.setObjectName("new_password2")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.new_password2.setFont(font)
        self.new_password2.setStyleSheet("color: GREY;")

        # 새 비밀번호 확인 입력창
        self.input_new_password2 = QtWidgets.QLineEdit(self.frame_2)
        self.input_new_password2.setGeometry(QtCore.QRect(600, 420, 500, 49))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.input_new_password2.setFont(font)
        self.input_new_password2.setObjectName("input_new_password2")

        # 변경하기 버튼
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_1.setGeometry(QtCore.QRect(600, 500, 154, 45))
        self.pushButton_1.setObjectName("pushButton_1")


        # 알림 설정 텍스트
        self.notification  = QtWidgets.QLabel(self.frame_2)
        self.notification.setGeometry(QtCore.QRect(307, 570, 281, 70))
        self.notification.setObjectName("notification")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.notification.setFont(font)

        # 알림 설정 버튼
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 580, 154, 45))
        self.pushButton_2.setObjectName("pushButton_1")


        # 회원탈퇴 텍스트
        self.withdraw = QtWidgets.QLabel(self.frame_2)
        self.withdraw.setGeometry(QtCore.QRect(307, 730, 281, 70))
        self.withdraw.setObjectName("withdraw ")
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.withdraw.setFont(font)

        # 회원탈퇴 버튼
        self.pushButton_3= QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 750, 154, 45))
        self.pushButton_3.setObjectName("pushButton_1")




        # 왼쪽 메뉴 프레임
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 141, 1079))
        self.frame.setStyleSheet("background-color: rgb(50, 90, 160)")  # 배경색 설정
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        # 메뉴-마이페이지 버튼
        self.menuButton_myPage_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_myPage_3.setGeometry(QtCore.QRect(30, 70, 84, 84))
        self.menuButton_myPage_3.setObjectName("menuButton_myPage_3")
        self.menuButton_myPage_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_myPage.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_myPage_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-트레이딩 버튼
        self.menuButton_trading_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_trading_3.setGeometry(QtCore.QRect(30, 211, 84, 84))
        self.menuButton_trading_3.setObjectName("menuButton_trading_3")
        self.menuButton_trading_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_trading.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_trading_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-거래(사고팔기) 버튼
        self.menuButton_chart_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_chart_3.setGeometry(QtCore.QRect(30, 351, 84, 84))
        self.menuButton_chart_3.setObjectName("menuButton_chart_3")
        self.menuButton_chart_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_chart.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_chart_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-자동거래 버튼
        self.menuButton_autoTrading_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_autoTrading_3.setGeometry(QtCore.QRect(30, 492, 84, 84))
        self.menuButton_autoTrading_3.setObjectName("menuButton_autoTrading_3")
        self.menuButton_autoTrading_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_autoTrading.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_autoTrading_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-환경설정 버튼
        self.menuButton_setting_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_setting_3.setGeometry(QtCore.QRect(30, 633, 84, 84))
        self.menuButton_setting_3.setObjectName("menuButton_setting_3")
        self.menuButton_setting_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_setting.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_setting_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        # 메뉴-종료 버튼
        self.menuButton_exit_3 = QtWidgets.QPushButton(self.frame)
        self.menuButton_exit_3.setGeometry(QtCore.QRect(30, 914, 84, 84))
        self.menuButton_exit_3.setObjectName("menuButton_exit_3")
        self.menuButton_exit_3.setStyleSheet(
            """
            QPushButton {
                border-image: url(resources/menu_exit.png);
                background-repeat: no-repeat;
            }
            QPushButton:pressed {
                border-image: url(resources/menu_exit_clicked.png);
                background-repeat: no-repeat;
            }
            """
        )

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Name.setText(_translate("MainWindow", "홍길동님"))
        self.label_change.setText(_translate("MainWindow", "비밀번호변경"))
        self.current_password.setText(_translate("MainWindow", "현재 비밀번호"))
        self.new_password.setText(_translate("MainWindow", "새 비밀번호"))
        self.new_password2.setText(_translate("MainWindow", "새 비밀번호 확인"))
        self.notification.setText(_translate("MainWindow", "알림 설정"))
        self.withdraw.setText(_translate("MainWindow", "회원탈퇴"))

        self.pushButton_1.setText(_translate("MainWindow", "변경하기"))
        self.pushButton_2.setText(_translate("MainWindow", "알림해지"))
        self.pushButton_3.setText(_translate("MainWindow", "탈퇴하기"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())